image: maven:latest

stages:
  - build
  - pretest
  - collection
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"
  POM: "-f DoNotDelete"
  DOCKER_AUTH_CONFIG: $CI_DOCKER_AUTH_CONFIG

cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $POM  $MAVEN_CLI_OPTS compile

Pass requirements:
  stage: pretest
  image: git.mylab.th-luebeck.de:4181/inf2praktikum/ctestenvironment
  script:
    - StartEnvironment $CI_PROJECT_DIR

ADTList:
  stage: collection
  script:
    - mvn $POM -Dtest=list.ADTListJqwikTest test

ADTStack:
  stage: collection
  script:
    - mvn $POM -Dtest=stack.ADTStackJqwikTest test

OneListQueue:
  stage: collection
  script:
    - mvn $POM -Dinclude.tests=queue.OneListQJqwikTest test
# -Dinclude.tests because of https://github.com/junit-team/junit5/issues/1406

TwoListQueue:
  stage: collection
  script:
    - mvn $POM -Dinclude.tests=queue.TwoListQJqwikTest test

ListSet:
  stage: collection
  script:
    - mvn $POM -Dinclude.tests=set.ListSetJqwikTest test

# TreeSet:
 # stage: collection
 # script:
  #  - mvn $POM -Dinclude.tests=set.TreeSetJqwikTest test

ListMap:
  stage: collection
  script:
    - mvn $POM -Dinclude.tests=map.ListMapJqwikTest test

TreeMap:
  stage: collection
  script:
    - mvn $POM -Dinclude.tests=map.TreeMapJqwikTest test

BST:
  stage: collection
  script:
    - mvn $POM -Dtest=tree.bst.TreeJqwikTest test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
